trigger:
- develop

pool:
  vmImage: ubuntu-latest
resources:
  repositories:
    - repository: AzureBoardsScript
      ref: master
      type: git
      name: Implementations
variables:
  - group: polaris-Kyle
steps:
- checkout: self
- bash: |
    curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $(Agent.TempDirectory) bridge.zip && rm -f bridge.zip
    $(Agent.TempDirectory)/synopsys-bridge --verbose --stage polaris \
      polaris.assessment.types='SAST,SCA' \
      polaris.application.name='kyleh' \
      polaris.project.name='ADO-BashTest' \
      polaris.branch.name=Bash \
      project.directory=WebGoat-Kyle
  env:
    BRIDGE_POLARIS_ACCESSTOKEN: $(BRIDGE_POLARIS_ACCESSTOKEN)
- checkout: AzureBoardsScript
- task: CmdLine@2
  inputs:
    script: |
     ls 
     cd Implementations/AzureBoardsScript
     ls
     python polaris_azure_ci.py --config "polaris-azure.conf" --polaris-application-name "kyleh" --polaris-project-name "ADO-BashTest" --polaris-branch-name Bash --polaris-severities-filter "''''critical'''',''''high'''',''''medium'''',''''low'''',''''info''''" --azure-project-name "PolarisTickets" --azure-iteration-path "iteration 2" --azure-area-path "area path test"
     cat logs/synopsys-azure.log
