name: Synopsys Security Testing

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.1.0
        with:
          blackduck_apiToken: MTU1NjczMWQtMjljMS00ZWQ1LWFkYzEtMTgyNzAxNjc3ZmIwOmI2Mzg3MmRiLWFiYTItNDZhOS05MjI2LTNkOGQxZjU3ODk2OQ==
          blackduck_url: https://us1a-sup-sheeley.nprd.sig.synopsys.com

          # Optional parameter. By default, pushes will initiate a full "intelligent" scan and pull requests
          # will initiate a rapid scan.
          blackduck_scan_full: true
          # Required parameter if blackduck_automation_fixpr is enabled
          # Make sure GITHUB_TOKEN have appropriate permissions
          github_token: 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
          # Optional parameter. By default, create fix pull requests if vulnerabilities are reported
          # Passing false will disable fix pull request creation 
          blackduck_automation_fixpr: true
          # Optional parameter. The values could be. ALL|NONE|BLOCKER|CRITICAL|MAJOR|MINOR|OK|TRIVIAL|UNSPECIFIED
          # Single parameter
          # blackduck_scan_failure_severities: "ALL"
          # multiple parameters
          # blackduck_scan_failure_severities: "BLOCKER,CRITICAL,TRIVIAL"
